### PR TITLE
Update to 1.7.3

### PR DESCRIPTION
**Pull request by djhoese**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by djhoese** [comment]
@conda-forge-admin please rerender

**Comment by djhoese** [comment]
CI needs restart when PyPI isn't doing maintenance.

**Comment by djhoese** [comment]
@conda-forge-admin please restart ci

**Comment by djhoese** [comment]
Oops still doing maintenance on PyPI.

**Comment by djhoese** [comment]
Ok this isn't a maintenance thing. For some reason 1.7.3 can't be downloaded with the pypi.io URL. @ocefpaf have you ever seen this before? The link on the PyPI page works fine.

**Comment by djhoese** [comment]
Ok good to know. Thanks!

**Comment by ocefpaf** [comment]
> Ok good to know. Thanks!

PyPI is changing URLs for packages like that. Many are broken b/c of it :-/

**Pull request merged**
